# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a086b7b2411a7006dede727144a780135ee9e631ec4640484d9d14c44c06d4ef31bcaecb7490f760ff7eb5f18e0d42d2028c917f137979d3f39bb6f11b725d67

test:
  secret_key_base: 0c739e113e7edf374ad7ac797aaf5feee739e4b77ef57b328b8651c686f363b74997bc83f391b27fb1fed6534343b9210e6dca38de19ae57f366fa48015b3c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
